Repository CBNU-FinFlow/Client, pull requests merged in 2025-03, with the labels that each got.

#17 [FEAT] 포트폴리오 추가/관리 페이지 추가
  src/app/(afterLogin)/_component/Navbar.tsx
  src/app/(afterLogin)/assets/page.tsx
  src/app/(afterLogin)/manage-portfolios/_component/DeletePortfolioModal.tsx
  src/app/(afterLogin)/manage-portfolios/_component/EditPortfolioModal.tsx
  src/app/(afterLogin)/manage-portfolios/page.tsx
  src/app/(afterLogin)/new-portfolio/page.tsx
  src/app/(afterLogin)/stats/page.tsx
  src/app/(beforeLogin)/auth/login/page.tsx
  src/app/store/modal.ts
Labels: feat, UI/UX

#18 [FEAT] zustand로 포트폴리오 전역 상태관리 기능 추가
  .prettierrc
  next.config.ts
  src/app/(afterLogin)/_component/Navbar.tsx
  src/app/(afterLogin)/layout.tsx
  src/app/(afterLogin)/manage-portfolios/_component/DeletePortfolioModal.tsx
  src/app/(afterLogin)/manage-portfolios/_component/EditPortfolioModal.tsx
  src/app/(afterLogin)/manage-portfolios/page.tsx
  src/app/(afterLogin)/new-portfolio/page.tsx
  src/app/(beforeLogin)/auth/login/page.tsx
  src/app/store/usePortfolioStore.ts
  src/utils/axiosInstance.ts
Labels: feat

#23 [feat] 보유 자산 페이지 백엔드 연동
  package-lock.json
  package.json
  src/app/(afterLogin)/assets/_component/DeleteAssetsModal.tsx
  src/app/(afterLogin)/assets/_component/TransferModal.tsx
  src/app/(afterLogin)/assets/page.tsx
  src/app/(afterLogin)/layout.tsx
  src/app/(afterLogin)/transactions/_component/AddInvestmentsModal.tsx
  src/app/layout.tsx
  src/model/Asset.ts
  src/model/FinancialProduct.ts
  src/utils/axiosInstance.ts
Labels: feat

#27 [fix] 거래 내역 페이지 수정
  src/app/(afterLogin)/transactions/_component/DeleteTransactionsModal.tsx
  src/app/(afterLogin)/transactions/page.tsx
  src/model/Transaction.ts
Labels: fix
